---
- name: Create and configure security group
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ sg_name }}"
    description: "{{ sg_name_description }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        - 8080
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80
  register: ec2_group

- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    instance_tags: 
      Name: "{{ instance_name }}"
    exact_count: 1
    count_tag: 
        Name: "{{ instance_name }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    image: "{{ ami }}"
    instance_type: "{{ instance_type }}"
    group: "{{ sg_name }}"
    vpc_subnet_id: "{{ public_subnet_id }}"
    assign_public_ip: yes
    wait: yes
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

    