---

- name: Install Prerequisites
  package: name={{item}} state=present
  with_items:
    - oracle-java8-installer
    - mysql

- name: Download SonarQube
  get_url: 
    url: "{{ URL_TO_DOWNLOAD_SONARQUBE }}" 
    dest: /opt

- name: Extract SonarQube into /opt/sonar
  unarchive: 
    src: sonarqube-{{ version }}.zip
    dest: /opt/sonar

- name: Modify sonar propertiles file
  replace:
    path: /opt/sonar/conf/sonar.properties
    regex:
    replace:
  with_items:
    - "{ '{{ #sonar.jdbc.username= }}': { 'sonar.jdbc.username= sonar'} }"
    - "{ '{{ #sonar.jdbc.password= }}': { 'sonar.jdbc.username= sonar'} }"

- name: Run SonarQube as a default service
  become: yes
  copy:
    src: /opt/sonar/bin/linux-x86-64/sonar.sh
    dest: /etc/init.d/sonar

- name: Modify sonar file
  lineinfile:
    path: /etc/init.d/sonar
    regex: '^SONAR_HOME='
    line: SONAR_HOME=/opt/sonar
